# Generated by Django 5.0.2 on 2024-03-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_country_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_key',
            field=models.CharField(blank=True, null=True),
        ),
    ]
