# Generated by Django 4.2.10 on 2024-03-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('set_canceled', 'Can cancel products')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
